eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
limits-service:
  minimum: 99
  maximum: 999
